# Generated by Django 4.0.6 on 2022-09-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_alter_customuser_fav_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
